accounts/urls.py
from django.urls import path

from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

api/urls.py
from django.urls import path, include

from rest_framework.routers import SimpleRouter

# from .views import ProjectListAPI, ProjectDetailAPI, TaskListAPI, TaskDetailAPI
from .views import ProjectViewSet, TaskViewSet

router = SimpleRouter()
router.register('projects', ProjectViewSet, basename='projects')
router.register('tasks', TaskViewSet, basename='tasks')

urlpatterns = [
    # path('projects/', ProjectListAPI.as_view(), name='project-list-api'),
    # path('projects/<int:pk>/', ProjectDetailAPI.as_view(), name='project-detail-api'),
    # path('tasks/', TaskListAPI.as_view(), name='task-list-api'),
    # path('tasks/<int:pk>/', TaskDetailAPI.as_view(), name='task-detail-api'),
    path('api-auth/', include('rest_framework.urls')),
    # path('rest-auth/', include('rest_auth.urls')),
    path('', include('rest_auth.urls')),
    path('register/', include('rest_auth.registration.urls')),
    # path('rest-auth/registration/', include('rest_auth.registration.urls')),
]

urlpatterns += router.urls

backend/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.ProjectListView.as_view(), name='projects'),
    path('create', views.ProjectCreateView.as_view(), name='project-create'),
    path('task/create', views.TaskCreateView.as_view(), name='task-create'),
    path('<int:pk>/delete', views.ProjectDeleteView.as_view(), name='project-delete'),
    path('<int:pk>/update', views.ProjectUpdateView.as_view(), name='project-update'),
    path('task/<int:pk>/delete', views.TaskDeleteView.as_view(), name='task-delete'),
    path('task/<int:pk>/update', views.TaskUpdateView.as_view(), name='task-update'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # views
    path('', include('backend.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),

    # rest-api
    path('api/', include('api.urls')),
]

api/models.py
from django.db import models

# Create your models here.

backend/models.py
from django.db import models
from django.contrib.auth.models import User


class Project(models.Model):
    project_name = models.CharField(max_length=150, default='', verbose_name='Проект')
    user = models.ForeignKey(User, null=True,
                             on_delete=models.CASCADE, verbose_name='Пользователь')

    class Meta:
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'

    def __str__(self):
        return self.project_name[:50]


class Task(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, verbose_name='Проект')
    task_name = models.CharField(max_length=250, default='', verbose_name='Задача')
    is_done = models.BooleanField(default=False, verbose_name='Выполнено')

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'

    def __str__(self):
        return self.task_name[:50]

accounts/views.py
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'register.html'

api/views.py
# from rest_framework import generics
from rest_framework import viewsets

from backend.models import Project, Task
from backend.mixins import ProjectMixin, TaskMixin

from .mixins import ProjectAPIMixin
from .serializers import ProjectSerializer, TaskSerializer


class ProjectViewSet(ProjectMixin, ProjectAPIMixin, viewsets.ModelViewSet):
    queryset = Project.objects.all()
    serializer_class = ProjectSerializer


class TaskViewSet(TaskMixin, viewsets.ModelViewSet):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer

# class ProjectListAPI(ProjectMixin, ProjectAPIMixin, generics.ListCreateAPIView):
#     model = Project
#     serializer_class = ProjectSerializer
#
#
# class ProjectDetailAPI(ProjectMixin, ProjectAPIMixin, generics.RetrieveUpdateDestroyAPIView):
#     model = Project
#     serializer_class = ProjectSerializer


# class TaskListAPI(TaskMixin, generics.ListCreateAPIView):
#     model = Task
#     serializer_class = TaskSerializer
#
#
# class TaskDetailAPI(TaskMixin, generics.RetrieveUpdateDestroyAPIView):
#     model = Task
#     serializer_class = TaskSerializer

backend/views.py
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .models import Project, Task
from .mixins import ProjectMixin, TaskMixin


class ProjectListView(LoginRequiredMixin, ProjectMixin, ListView):
    model = Project
    context_object_name = 'projects'


class ProjectCreateView(LoginRequiredMixin, ProjectMixin, CreateView):
    model = Project
    fields = ('project_name',)
    success_url = reverse_lazy('projects')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ProjectUpdateView(LoginRequiredMixin, ProjectMixin, UpdateView):
    model = Project
    fields = ('project_name',)
    template_name = 'backend/project_update_form.html'
    success_url = reverse_lazy('projects')


class ProjectDeleteView(LoginRequiredMixin, ProjectMixin, DeleteView):
    model = Project
    success_url = reverse_lazy('projects')


class TaskCreateView(LoginRequiredMixin, TaskMixin, CreateView):
    model = Task
    fields = '__all__'
    success_url = reverse_lazy('projects')

    def get_form(self, *args, **kwargs):
        form_class = super().get_form(form_class=None)

        form_class.fields['project'].choices =\
            [(project.pk, project) for project in Project.objects.filter(user=self.request.user)]

        return form_class


class TaskUpdateView(LoginRequiredMixin, TaskMixin, UpdateView):
    model = Task
    fields = ('task_name', 'is_done',)
    template_name = 'backend/task_update_form.html'
    success_url = reverse_lazy('projects')


class TaskDeleteView(LoginRequiredMixin, TaskMixin, DeleteView):
    model = Task
    success_url = reverse_lazy('projects')

accounts/templates/_base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block meta_tags %}{% endblock %}
    <title>{% block title %}Authentication{% endblock %}</title>

    {% block css %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/mycss.css' %}">
</head>
<body>

<div class="container mt-4">
    <div class="row h-100 justify-content-center align-items-center">
        {% block container %}
        {% endblock %}
    </div>
</div>

{% block js %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
{% endblock %}

</body>
</html>

accounts/templates/register.html
{% extends "_base.html" %}
{% block container %}
{% load crispy_forms_tags %}
<div class="card bg-light mb-3" style="max-width: 26rem;">
    <div class="card-header">
        <h5 class="card-title">Регистрация нового пользователя</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-dark btn-block">Отправить</button>
        </form>
        <hr>
        <p></p>Уже есть аккаунт? <a href="{% url 'login' %}">Вернуться</a></p>
    </div>
</div>
{% endblock %}

authentication/templates/register.html
{% extends "_base.html" %}
{% block container %}
<div class="container" style="max-width: 360px;">
    <div class="row">
        <div class="panel panel-primary">
            <div class="panel-body">
                <form method="POST" role="form">
                    {% csrf_token %}

                    <div class="form-group">
                        <h2 style="margin-top: 2px; margin-bottom: 2px;">Регистрация</h2>
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="id_username">Имя:</label>
                        <input class="form-control" type="text" name="username" value="qwe" maxlength="150" autocapitalize="none" autocomplete="username" autofocus required id="id_username">
                        <span class="helptext">Только буквы, цифры и символы @/./+/-/_.</span>
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="id_password1">Пароль:</label>
                        <input class="form-control" type="password" name="password1" autocomplete="new-password" required id="id_password1">
                        <span class="helptext">
                            <ul>
                                <li>Пароль не должен быть слишком похож на другую вашу личную информацию.</li>
                                <li>Ваш пароль должен содержать как минимум 8 символов.</li>
                                <li>Такой пароль часто используется.</li>
                                <li>Пароль не может состоять только из цифр.</li>
                            </ul>
                        </span>
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="id_password2">Подтверждение пароля:</label>
                        <input class="form-control" type="password" name="password2" autocomplete="new-password" required id="id_password2">
                    </div>

                    <div class="form-group">
                        <button id="signupSubmit" type="submit" class="btn btn-info btn-block">Создать аккаунт</button>
                    </div>
                    <hr>
                    <p></p>Уже есть аккаунт? <a href="{% url 'login' %}">Вернуться</a></p>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/backend/project_confirm_delete.html
{% extends "base.html" %}
{% block container %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Удаление проекта</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="alert alert-warning" role="alert">
                Вы уверены, что хотите удалить проект <strong>{{ project }}</strong> ?
            </div>
            <button type="submit" class="btn btn-danger">Удалить</button>
        </form>
    </div>
</div>
{% endblock %}

templates/backend/project_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block container %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Создать новый проект</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success">Создать</button>
        </form>
    </div>
</div>
{% endblock %}

templates/backend/project_list.html
{% extends "base.html" %}

{% block container %}

<ul class="nav nav-tabs" role="tablist">
    {% for project in projects %}
    <li class="nav-item">
        <a class="nav-link {% if project.id == projects.0.id %} active {% endif %}"
           id="project{{ project.id }}-tab"
           data-toggle="tab"
           href="#project{{ project.id }}"
           role="tab"
           aria-controls="project{{ project.id }}"
           aria-selected="false">
            <span data-toggle="tooltip"
                  title="{{ project.project_name }}">{{ project.project_name|truncatechars:15 }}</span></a>
    </li>
    {% endfor %}
</ul>

<div class="tab-content">
    {% for project in projects %}
    <div class="tab-pane fade {% if project.id == projects.0.id %} show active {% endif %}" id="project{{ project.id }}"
         role="tabpanel"
         aria-labelledby="project{{ project.id }}-tab">
        <table class="table table-hover">
            <tr>
                <thead class="thead-light">
                <tr>
                    <th scope="col">Список задач</th>
                    <th scope="col" class="text-right">
                        <a href="{{ project.id }}/delete">
                            <button class="btn btn-sm btn-dark">
                                Удалить
                            </button>
                        </a>
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for task in project.task_set.all %}
                <tr>
                    <td>
                        <span {% if task.is_done %} style="text-decoration: line-through;" {% endif %}>
                            <a href="/task/{{ task.id }}/update">{{ task.task_name }}</a>
                        </span>
                    </td>
                    <td class="text-right">
                        <a href="/task/{{ task.id }}/delete">
                            <button class="btn btn-sm btn-danger">
                                Удалить
                            </button>
                        </a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
        </table>
        <div class="card-header text-right">
            <a href="/{{ project.id }}/update">
                <button class="btn btn-sm btn-dark" style="margin-right: -5px;">
                    Править
                </button>
            </a>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

templates/backend/project_update_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block container %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Изменить проект</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success">Применить</button>
        </form>
    </div>
</div>
{% endblock %}

templates/backend/task_confirm_delete.html
{% extends "base.html" %}
{% block container %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Удаление задачи</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="alert alert-warning" role="alert">
                Вы уверены, что хотите удалить задачу <strong>{{ task }}</strong> ?
            </div>
            <button type="submit" class="btn btn-danger">Удалить</button>
        </form>
    </div>
</div>
{% endblock %}

templates/backend/task_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block container %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Добавить новую задачу</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success">Добавить</button>
        </form>
    </div>
</div>
{% endblock %}

templates/backend/task_update_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block container %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Изменить задачу</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success">Применить</button>
        </form>
    </div>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="#">
    {% block meta_tags %}{% endblock %}
    <title>{% block title %}Task manager{% endblock %}</title>

    {% block css %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/mycss.css' %}">

    <!--    if not use LoginRequiredMixin -->
    <!--    {% if not user.is_authenticated %}-->
    <!--    <meta http-equiv="REFRESH" content="0;url={% url 'login' %}">-->
    <!--    {% endif %}-->
</head>
<body>

{% block navbar %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <div class="container">
        <a class="navbar-brand" href="{% url 'projects' %}">Менеджер задач</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Добавить
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                    <a class="dropdown-item" href="{% url 'project-create' %}">Проект</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'task-create' %}">Задачу</a>
                </div>
            </li>
        </ul>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                        <a class="dropdown-item" href="{% url 'password_change' %}">Сменить пароль</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}">Выйти</a>
                    </div>
                </li>
            </ul>
            {% else %}
            <form class="form-inline ml-auto">
                <a href="{% url 'login' %}" class="btn btn-outline-secondary">Войти</a>
                <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Регистрация</a>
            </form>
            {% endif %}
        </div>

    </div>
</nav>
{% endblock %}

<div class="container mt-4">
    {% block container %}
    {% endblock %}
</div>

{% block js %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
{% endblock %}

{% block custom_js %}
<script>
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })
</script>
{% endblock %}
</body>
</html>